### ISSUE TITLE
A few issues with landing page

### ISSUE THREAD

**Issue by clement-lee** [elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep#112]
Now that the training page is made "visible" on https://elixir-europe-training.github.io/CodeReproducibility/lessons/, there are a few things on the landing page we have to fix:

1. Citation: Should the title be **Elisa Pierfederici, Clement Lee, Saad Arif, & Mark Fernandes (2024). Literate Programming in R**?
2. And how do we generate the DOI? (Maybe raise this in the All Teams meeting)?
3. Data Setup: An easy fix is to have the scripts and data in this repo, and ask the learner to download them.
4. Software Setup: This is partly covered in Chapter 4. Shall we simply link to its occurrence in Chapter 4, or the other way round (link from Chapter 4 to here), or keep them separate?
5. At the top of the landing page it still says "This lesson is under active development and considered pre-alpha." How do we remove this?

**Comment by saadarif** [comment]
> 1. Citation: Should the title be Elisa Pierfederici, Clement Lee, Saad Arif, & Mark Fernandes (2024). Literate Programming in R?
> 2. And how do we generate the DOI? (Maybe raise this in the All Teams meeting)?

I think we can upload the entire repositry to something like [zenodo](https://zenodo.org/), which can then generate a DOI. Lets bring this up at the all Teams meeting?

>3.  Data Setup: An easy fix is to have the scripts and data in this repo, and ask the learner to download them. The data (any other dependencies) would be required to start on the chapter 5 exercise.

That would make things easier. We could then have links to direct download. This would be necessary for the final exercise 

> 4. Software Setup: This is partly covered in Chapter 4. Shall we simply link to its occurrence in Chapter 4, or the other way round (link from Chapter 4 to here), or keep them separate?``

I think the original plan was to remove any such occurences from indivdual chapters and have them up front on the landing page. But there could be a case for the other way round?

> 5. At the top of the landing page it still says "This lesson is under active development and considered pre-alpha." How do we remove this?

let's bring this up at the All teams meeting tomorrow as well.

**Comment by mfernandes61** [comment]
2. https://open.win.ox.ac.uk/pages/open-science/community/Open-WIN-Community/docs/gitlab/4-2-you-doi/#:~:text=In%20zenodo%2C%20log%20in%20or,on%20GitLab%2C%20or%20other%20documentation.
5. I have edited the header on landing page to remove pre-alpha message.

**Comment by clement-lee** [comment]
1. (to be) resolved by #113 
2. (to be) resolved by #113
3. fixed #117
4. fixed #117 
5. fixed above
