### ISSUE TITLE
Chapter 2 - style suggestion

### ISSUE THREAD

**Issue by mfernandes61** [elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep#59]
Can I suggest that wherever a filetype is referred to e.g. .R or .qmd that it be highlighted (in bold?)
i.e. **.R** or **.qmd**
This will emphasise it to the student

**Comment by mfernandes61** [comment]
You've made me think further about this. I had intended just the .<filetype> references as they could get lost in normal punctuation but you've made a good point - it may be a better practice to embolden the full filename examples too to emphasise them to reader.

**Comment by clement-lee** [comment]
Done for both . references and full filename in #76
