### ISSUE TITLE
Chapter 2 - YAML explanation

### ISSUE THREAD

**Issue by mfernandes61** [elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep#60]
Suggest that when YAML is introduced in "the components" paragraph that the abbreviation is explained or a link to an explanatory article be supplied e.g. https://en.wikipedia.org/wiki/YAML

Similarly, it may be advisable to link to further info on panic when it is mentioned at end of Chapter 2 (as an option for those who wish to know more)

**Comment by clement-lee** [comment]
Added links for pandoc & YAML
