### ISSUE TITLE
Chapter 1: centre Knuth image?

### ISSUE THREAD

**Issue by saadarif** [elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep#67]
for consistency

**Comment by mfernandes61** [comment]
doing build. awkward to do as using HTML to pull the wikipedia Knuth image so having to use div & inline style. Will see if it worked after MKDoc build finishes

**Comment by mfernandes61** [comment]
fixed 
example code:
 <div style="text-align: center;">
         <img width="500" src="https://website.org/picture.jpg">
      </div>

**Comment by mfernandes61** [comment]
done
