### ISSUE TITLE
Chapter 1: typos

### ISSUE THREAD

**Issue by saadarif** [elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep#68]
Section 1.2 "reads' - mismatched quotes
Section 1.2 break needed after first pargraph
Section 1.2 paranthesis in 2nd paragraph opened but not closed
Section 1.2 3rd para : typo "enbles"

**Comment by mfernandes61** [comment]
Fixed (but couldn't find the unclosed parentheses...)
