### ISSUE TITLE
Chapter 2: typos and suggestions

### ISSUE THREAD

**Issue by saadarif** [elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep#69]
"4. plain text files (.tex)" - if some of the audience is like me, plain text files would be .txt or .csv files. Additionally, some of our audience may not be familiar with .tex files at this stage. Not sure if this matters though...

"...you are likely to collaborate through Overleaf.." - not a typo per se but I think this would sound alien to most researchers from a more biological background. How about "..you may potentially collaborate through a tool such as Overleaf..." something along those lines as not to potentially scare away some of the audience

"What do you do when that happens? you re-run the scripts.." - Capitalize after question mark

Add link to pandoc for the curious

Add section numbering for consistency across pages

**Comment by clement-lee** [comment]
Fixed all issues in #76
