### ISSUE TITLE
Chapter 2: Suggestion for an addition

### ISSUE THREAD

**Issue by saadarif** [elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep#70]
I think this section needs an exercise or two to reinforce the main point(s). Since no actual technique are introduced, and this is a high-level layout for the following 2 chapters, the exercise(s) could be open-ended questions as in chapter 1. Some of the questions you pose under the sections "First Pass" and/or "Reproducibility" could be rejigged as exercises for the students? Or could be something else entirely.

**Comment by clement-lee** [comment]
Added this in #76
